services:
    www:
        build: docker
        ports: 
            - "80:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: krant
            MYSQL_USER: thijs
            MYSQL_PASSWORD: krant
            MYSQL_ROOT_PASSWORD: krant
        volumes:
            - ./sql/init:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: thijs
            MYSQL_PASSWORD: krant
            MYSQL_ROOT_PASSWORD: krant
    npm:
        image: node:22
        volumes:
            - ./www:/var/www/html/
        working_dir: /var/www/html
        command: /bin/true
volumes:
    persistent: